import type { ChartData } from './types';

// 액션 키: R = Raise, C = Call, M = Mix(상황 혼합), F = Fold
// detailedReason는 "왜 그 액션인가"를 포지션/핸드 속성(절대강도, 도미네이션, 플레이어빌리티, 폴드 이퀴티, 멀티웨이 리스크, 블로커, 리얼라이제이션) 기준으로 설명합니다.
// examples는 실제 결정을 떠올리기 좋은 짧은 사례 문장입니다.

export const CHART_DATA: ChartData = {
  UTG: {
    // --- Premium & High Pairs ---
    AA: { action: 'R', reason: '최강 핸드. 무조건 레이즈', detailedReason: '절대 강도 최상. 멀티웨이에서도 에퀴티 우위가 커서 프리플랍부터 밸류 극대화가 필요합니다.', examples: ['3-bet에 4-bet 대응 가능', '멀티웨이에서도 유리', '플랍 텍스처 영향 적음'] },
    KK: { action: 'R', reason: 'AA 다음 프리미엄', detailedReason: '오버카드로 A만 주의하면 되고, 주도권을 갖고 팟을 키우는 편이 EV가 큽니다.', examples: ['A 하이 보드 체크-콜/컨트롤', '3-bet 포트에서도 밸류', '4-bet 콜/샤브 고려'] },
    QQ: { action: 'R', reason: '프리미엄 페어', detailedReason: 'A/K 오버카드 리스크는 있으나 전반적으로 강력. 타이트 UTG 레인지로 밸류 오픈.', examples: ['A,K 보드에서 사이즈 다운 C-bet', '3-bet에 포지션/스택따라 콜/4-bet'] },
    JJ: { action: 'R', reason: '상위 중페어', detailedReason: '오버카드가 종종 뜨지만 헤즈업에선 쇼다운 밸류 충분. 프리에서 주도권을 잡는 것이 유리.', examples: ['드라이 보드 C-bet 빈도↑', 'KQx 보드에선 컨트롤'] },
    TT: { action: 'R', reason: '중상급 페어', detailedReason: '셋 밸류 + 쇼다운 밸류 조합. 멀티웨이 방지 목적의 오픈이 좋습니다.', examples: ['작은 3-bet엔 콜, 큰 3-bet엔 폴드'] },
    '99': { action: 'R', reason: '중급 페어', detailedReason: '셋 마이닝 기대 + 주도권. 뒤에서 공격 받으면 폴드 빈도 존재.', examples: ['플랍 오버카드 많으면 컨트롤', '3-bet 큰 사이즈엔 폴드'] },
    '88': { action: 'R', reason: '중급 페어', detailedReason: '유연하지만 역스팟 많음. 오픈으로 스틸/필드 축소.', examples: ['멀티웨이 피하기', '셋 미스 시 과도한 바렐 지양'] },
    '77': { action: 'R', reason: '하위 중페어', detailedReason: '셋 의존도가 있어도 오픈-주도권이 EV를 보정.', examples: ['플랍 로우보드 C-bet', '오버카드 다수면 체크'] },

    // --- Suited Broadways & Aces ---
    AKs: { action: 'R', reason: '프리미엄 브로드웨이 수딧', detailedReason: '탑페어 탑키커 빈번 + 넛 플러시 잠재력 + 에이스/킹 블로커. 프리/포스트 모두 강력한 압력.', examples: ['3-bet 케이스에서도 강하게', '탑페어로 2배럴 가치'] },
    AQs: { action: 'R', reason: '강한 수딧 에이스', detailedReason: '쇼다운 밸류와 드로우 밸류 동시에 보유. 블로커로 3-bet 빈도 제어.', examples: ['AQx 보드 밸류 C-bet', '백도어 플러시로 세미블러프'] },
    AJs: { action: 'R', reason: '수딧 에이스', detailedReason: '플레이어빌리티 양호하나 멀티웨이에 취약. 오픈으로 필드 축소.', examples: ['A하이 보드 밸류', 'KQx 보드 컨트롤'] },
    ATs: { action: 'R', reason: '수딧 에이스(하위)', detailedReason: '세미블러프 루트와 쇼다운 밸류 공존. 주도권 확보가 핵심.', examples: ['백도어 + 턴 배럴', '어그로 테이블에선 빈도↓'] },
    KQs: { action: 'R', reason: '수딧 브로드웨이', detailedReason: '스트/플러시 드로우가 많은 텍스처에서 강력. 도미네이션 주의.', examples: ['T9x, JTx 보드 압박', 'A하이 보드 체크 빈도↑'] },
    KJs: { action: 'M', reason: '경계선 수딧 킹', detailedReason: '도미네이션 리스크(KQ, AJ 등). 테이블이 타이트하면 소량 오픈, 공격적이면 폴드혼합.', examples: ['넛 드로우 땐 공격', '3-bet 큰 사이즈엔 폴드'] },
    QJs: { action: 'M', reason: '경계선 수딧 퀸', detailedReason: '플레이어빌리티는 좋지만 UTG에선 뒤 포지션의 3-bet/콜에 취약. 혼합 사용.', examples: ['딥스택엔 조금 더 개방', '쇼트스택엔 보수적'] },

    // --- Offsuit Broadways ---
    AKo: { action: 'R', reason: '최강 오프수트', detailedReason: '탑페어 최상 키커 빈번 + 블로커. 프리폴드 이퀴티 확보.', examples: ['3-bet에 4-bet 믹스', 'A/K 하이 보드 밸류'] },
    AQo: { action: 'R', reason: '강력 오프수트', detailedReason: '도미네이션 우위(Ax) + 블로커. 포지션 불리 보정 위해 주도권 필수.', examples: ['AQx에서 밸류', 'K하이 보드 컨트롤'] },
    AJo: { action: 'M', reason: '경계선 오프수트', detailedReason: '리얼라이제이션 저하 + 역도미네이션 위험. 타이트 테이블에서 일부 오픈.', examples: ['루즈 테이블 폴드', '3-bet 빈도 높으면 폴드'] },

    // --- Suited Wheel Aces ---
    A5s: { action: 'M', reason: '휠/넛 플러시 잠재력', detailedReason: '휠 스트/넛 플러시 백도어 강점. 앞자리라 빈도 제한.', examples: ['딥스택일수록 가치↑', '공격적 테이블 빈도↓'] },
    A4s: { action: 'M', reason: '휠 계열', detailedReason: 'A5s 유사. 스틸 가치 낮은 UTG라 빈도 조절.', examples: ['후속 배럴 플랜 필요', '루즈 콜러 많으면 폴드'] },
    A3s: { action: 'M', reason: '낮은 수딧 에이스', detailedReason: '역도미네이션/멀티웨이 취약. 혼합 사용.', examples: ['버티컬 바렐 자제', '포지션 불리 인식'] },
    A2s: { action: 'M', reason: '낮은 수딧 에이스', detailedReason: '휠 스트레이트 가능성은 있으나 전반 파워 낮음.', examples: ['딥스택에서만 소량', '3-bet 큰 사이즈 폴드'] },
  },

  MP: {
    AA: { action: 'R', reason: '프리미엄', detailedReason: 'UTG와 동일 논리. 밸류 극대화.', examples: ['3-bet 유도 OK', 'A하이 보드 강공'] },
    KK: { action: 'R', reason: '프리미엄', detailedReason: '오픈으로 필드 축소 + 밸류 실현.', examples: ['A 보드 컨트롤', '딥스택 4-bet 고려'] },
    QQ: { action: 'R', reason: '프리미엄', detailedReason: '상위 오버카드 등장 전 밸류 확보.', examples: ['3-bet 콜/4-bet 믹스', 'AQK 보드 컨트롤'] },
    JJ: { action: 'R', reason: '강한 페어', detailedReason: '헤즈업에서 강력. 멀티웨이 방지 위해 오픈.', examples: ['드라이 보드 C-bet', '브로드웨이 보드 체크'] },
    TT: { action: 'R', reason: '중상급 페어', detailedReason: '셋 + 쇼다운 밸류 균형.', examples: ['플랍 오버카드 1~2장 컨트롤', '3-bet 작은 사이즈 콜'] },
    '99': { action: 'R', reason: '중급 페어', detailedReason: '필드 축소/주도권이 EV 보정.', examples: ['로우보드 압박', '딥스택 3-bet 콜'] },
    '88': { action: 'R', reason: '중급 페어', detailedReason: '셋 마이닝 + 포지션 개선.', examples: ['오버카드 많은 보드 체크백', '턴에서 포팅 자제'] },
    '77': { action: 'R', reason: '하위 중페어', detailedReason: '스틸 가치 소폭↑. 오픈 가능.', examples: ['멀티웨이 경계', '드로우 보드 주의'] },
    '66': { action: 'M', reason: '경계선 페어', detailedReason: '셋 미스 시 리얼라이제이션 낮음. 테이블 성향 따라 혼합.', examples: ['패시브 테이블 오픈', '어그로 테이블 폴드'] },

    AKs: { action: 'R', reason: '프리미엄', detailedReason: '블로커 + 넛 잠재력. 3-bet에도 강.', examples: ['백도어 + 더블배럴', '탑페어 밸류'] },
    AQs: { action: 'R', reason: '강한 수딧', detailedReason: '탑페어/넛 드로우 동시 보유.', examples: ['AQx 밸류', '플러시 드로우 세미블러프'] },
    AJs: { action: 'R', reason: '수딧 에이스', detailedReason: '도미네이션 리스크 있으나 수딧 보정.', examples: ['A하이 보드 밸류', 'KQx 컨트롤'] },
    ATs: { action: 'R', reason: '수딧 에이스', detailedReason: '세미블러프 루트 풍부.', examples: ['백도어 + 턴 배럴', '블라인드 타이트시 오픈↑'] },
    A9s: { action: 'M', reason: '마진 수딧', detailedReason: '쇼다운/도미네이션 중간. 패시브면 오픈 혼합.', examples: ['공격적 블라인드 폴드', '타이트 블라인드 오픈'] },

    KQs: { action: 'R', reason: '수딧 브로드웨이', detailedReason: '플레이어빌리티 탁월.', examples: ['JT9 보드 압박', 'A하이 보드 컨트롤'] },
    KJs: { action: 'R', reason: '수딧 킹', detailedReason: '콜다운/세미블러프 라인 모두 양호.', examples: ['톱페어 약키커 컨트롤', '턴 이퀴티로 배럴'] },
    QJs: { action: 'R', reason: '수딧 퀸', detailedReason: '스트/플러시 드로우 다수.', examples: ['샷건/플러시 드로우로 압박', '리버 블러프 카드 활용'] },
    JTs: { action: 'R', reason: '수딧 커넥터', detailedReason: '멀티웨이에서도 작동. 주도권 확보.', examples: ['보드 히트 없으면 저렴히'] },

    AKo: { action: 'R', reason: '강력 오프수트', detailedReason: '블로커 + 탑페어 가치.', examples: ['3-bet에 콜/4-bet 믹스', '브로드웨이 보드 강공'] },
    AQo: { action: 'R', reason: '강력 오프수트', detailedReason: '콜보다 오픈으로 필드 축소.', examples: ['AQx 밸류', 'K하이 보드 컨트롤'] },
    AJo: { action: 'R', reason: '중간 오프수트', detailedReason: '포지션 보정으로 오픈 가능.', examples: ['3-bet 강하면 폴드', '루즈 콜러 적으면 오픈↑'] },
    KQo: { action: 'M', reason: '경계선 오프수트', detailedReason: '리얼라이제이션 낮아 혼합.', examples: ['블라인드 타이트시 오픈', '공격적 3-bet 테이블 폴드'] },
    A5s: { action: 'M', reason: '휠 수딧', detailedReason: '휠/넛 플러시 잠재력. 빈도 제한.', examples: ['딥스택 가치↑', '스퀴즈 빈번시 폴드'] },
    A4s: { action: 'M', reason: '휠 수딧', detailedReason: 'A5s 유사.', examples: ['후속 플랜 확보', '블라인드 성향 반영'] },
    A3s: { action: 'M', reason: '낮은 수딧 A', detailedReason: '역도미네이션/멀티웨이 취약.', examples: ['소량 오픈', '3-bet 큰 사이즈 폴드'] },
    A2s: { action: 'M', reason: '낮은 수딧 A', detailedReason: '전반 파워 낮음.', examples: ['딥스택 국한', '패시브 테이블만'] },
  },

  CO: {
    AA: { action: 'R', reason: '프리미엄', detailedReason: '밸류 극대화. 뒤에 3명만 남아 스틸/밸류 모두↑.', examples: ['작게 오픈해 콜 유도', '3-bet엔 4-bet 믹스'] },
    KK: { action: 'R', reason: '프리미엄', detailedReason: '오버카드로 A만 주의하면 되고, 주도권을 갖고 팟을 키우는 편이 EV가 큽니다.', examples: ['A보드 컨트롤', '딥스택 4-bet 고려'] },
    QQ: { action: 'R', reason: '프리미엄', detailedReason: 'A/K 오버카드 리스크는 있으나 전반적으로 강력. 타이트 CO 레인지로 밸류 오픈.', examples: ['AQK 보드 컨트롤', '브릭 보드 강공'] },
    JJ: { action: 'R', reason: '강한 페어', detailedReason: '포지션 우위로 플레이 쉬움.', examples: ['드라이 보드 C-bet', '턴 카드 평가 후 2배럴'] },
    TT: { action: 'R', reason: '중상급 페어', detailedReason: '오픈으로 주도권.', examples: ['딥스택 셋 밸류', '오버카드 1~2장 컨트롤'] },
    '99': { action: 'R', reason: '중페어', detailedReason: '스틸 가치 + 포지션.', examples: ['블라인드 타이트면 오픈 가치↑'] },
    '88': { action: 'R', reason: '중페어', detailedReason: '오픈 표준.', examples: ['하이보드 컨트롤', '로우보드 압박'] },
    '77': { action: 'R', reason: '중페어', detailedReason: '후반 포지션 보정.', examples: ['멀티웨이 위험 낮음'] },
    '66': { action: 'R', reason: '로우 페어', detailedReason: '포지션이 좋아 빈도↑.', examples: ['셋 마이닝 + 스틸'] },
    '55': { action: 'M', reason: '경계선 로우 페어', detailedReason: '셋 의존. 블라인드 성향 따라 혼합.', examples: ['타이트 블라인드 오픈', '공격적 스퀴즈 폴드'] },

    AKs: { action: 'R', reason: '프리미엄', detailedReason: '스틸 + 포스트 이점.', examples: ['AQK 보드 강공', '깊은 스택 4-bet 고려'] },
    AQs: { action: 'R', reason: '강한 수딧', detailedReason: '넛 플러시/탑페어 라인.', examples: ['백도어로 배럴', '리버 밸류 얇게'] },
    AJs: { action: 'R', reason: '수딧 A', detailedReason: '포지션 우위로 컨트롤 용이.', examples: ['A하이 보드 밸류', '브로드웨이 보드 컨트롤'] },
    ATs: { action: 'R', reason: '수딧 A', detailedReason: '세미블러프 루트.', examples: ['백도어 + 더블배럴'] },
    A9s: { action: 'R', reason: '수딧 A(마진↑)', detailedReason: '후반 포지션 버프로 오픈.', examples: ['블라인드가 타이트하면 오픈 가치↑'] },
    A8s: { action: 'M', reason: '마진 수딧 A', detailedReason: '상대/스택에 따라 혼합.', examples: ['딥스택 오픈', '공격적 3-bet 빈번시 폴드'] },

    KQs: { action: 'R', reason: '수딧 브로드웨이', detailedReason: '강력한 텍스처 커버리지.', examples: ['T9x/JTx 압박'] },
    KJs: { action: 'R', reason: '수딧 킹', detailedReason: '후반 포지션으로 라인 선택 폭↑.', examples: ['톱페어 약키커 컨트롤'] },
    KTs: { action: 'R', reason: '수딧 킹(마진)', detailedReason: '도미네이션 위험 있지만 포지션 보정.', examples: ['블라인드 타이트시 오픈'] },
    QJs: { action: 'R', reason: '수딧 퀸', detailedReason: '드로우 다양. C-bet 빈도↑.', examples: ['세미블러프 카드 풍부'] },
    QTs: { action: 'R', reason: '수딧 퀸(마진)', detailedReason: '포지션이 커버.', examples: ['턴 배럴로 폴드 유도'] },
    JTs: { action: 'R', reason: '수딧 커넥터', detailedReason: '핸드 리딩 난이도↑로 수익성 우수.', examples: ['멀티웨이에서도 OK'] },
    T9s: { action: 'R', reason: '수딧 커넥터', detailedReason: '플레이어빌리티 탁월.', examples: ['하이보드에선 컨트롤'] },
    '98s': { action: 'R', reason: '수딧 커넥터', detailedReason: '유연성 최고. 스틸 가치↑.', examples: ['스퀴즈 당하면 혼합 대응'] },

    AKo: { action: 'R', reason: '강력 오프수트', detailedReason: '스틸 + 탑페어 가치.', examples: ['3-bet 콜/4-bet 믹스'] },
    AQo: { action: 'R', reason: '강력 오프수트', detailedReason: '밸류/블러프 캐치 라인 모두 존재.', examples: ['AQx 밸류', '블라인드 공격적이면 컨트롤'] },
    AJo: { action: 'R', reason: '오프수트 A(마진)', detailedReason: '후반 포지션이라 오픈 가능.', examples: ['3-bet 빈번시 폴드'] },
    ATo: { action: 'M', reason: '경계선 오프수트', detailedReason: '리얼라이제이션 낮아 혼합.', examples: ['타이트 블라인드 오픈', '공격적 3-bet 폴드'] },
    KQo: { action: 'R', reason: '오프수트 브로드웨이', detailedReason: '후반 포지션 보정으로 오픈.', examples: ['KQx 밸류', 'A보드 컨트롤'] },
    KJo: { action: 'M', reason: '오프수트 킹(마진)', detailedReason: '블라인드 성향에 따라 혼합.', examples: ['타이트면 오픈', '라그 블라인드면 폴드'] },
    QJo: { action: 'M', reason: '오프수트 퀸(마진)', detailedReason: '혼합 사용.', examples: ['스틸 목적 소량'] },
  },

  BTN: {
    AA: { action: 'R', reason: '프리미엄 + 포지션', detailedReason: '밸류/폴드 이퀴티/포지션 우위 결합. 오픈 100%.', examples: ['작게 오픈해 콜 유도', '3-bet엔 4-bet 믹스'] },
    KK: { action: 'R', reason: '프리미엄', detailedReason: '밸류/폴드 이퀴티/포지션 우위 결합. 오픈 100%.', examples: ['A보드 컨트롤'] },
    QQ: { action: 'R', reason: '프리미엄', detailedReason: '밸류/폴드 이퀴티/포지션 우위 결합. 오픈 100%.', examples: ['브릭 보드 강공'] },
    JJ: { action: 'R', reason: '강한 페어', detailedReason: '포지션 우위로 라인 선택 폭↑.', examples: ['드라이 보드 C-bet'] },
    TT: { action: 'R', reason: '중상급 페어', detailedReason: '오픈 표준.', examples: ['오버카드 나와도 컨트롤'] },
    '99': { action: 'R', reason: '중페어', detailedReason: '스틸 가치↑.', examples: ['블라인드 타이트 시 수익↑'] },
    '88': { action: 'R', reason: '중페어', detailedReason: '표준 오픈.', examples: ['셋 히트 시 밸류 극대화'] },
    '77': { action: 'R', reason: '중페어', detailedReason: '표준 오픈.', examples: ['멀티웨이 위험 낮음'] },
    '66': { action: 'R', reason: '로우 페어', detailedReason: '포지션 우위로 수익화 가능.', examples: ['셋 미스 시 컨트롤'] },
    '55': { action: 'R', reason: '로우 페어', detailedReason: '후반 포지션이라 무난.', examples: ['스틸 + 셋 마이닝'] },
    '44': { action: 'R', reason: '로우 페어', detailedReason: '포지션 우위로 수익화 가능. 셋 마이닝 + 스틸.', examples: ['리버 얇은 밸류 시도'] },
    '33': { action: 'R', reason: '로우 페어', detailedReason: '포지션 우위로 수익화 가능. 셋 마이닝 + 스틸.', examples: ['플랍 미스 시 포기'] },
    '22': { action: 'R', reason: '로우 페어', detailedReason: '포지션 우위로 수익화 가능. 셋 마이닝 + 스틸.', examples: ['딥스택 가치↑'] },

    AKs: { action: 'R', reason: '프리미엄 수딧', detailedReason: '넛 잠재력 + 포지션. 스틸/트랩 모두 가능.', examples: ['콤보드로 2배럴', '3-bet에 콜/4-bet 믹스'] },
    AQs: { action: 'R', reason: '강한 수딧', detailedReason: '탑페어/넛 드로우 라인 풍부.', examples: ['AQx 얇은 밸류', '백도어 압박'] },
    AJs: { action: 'R', reason: '수딧 A', detailedReason: '포지션 덕에 도미네이션 리스크 완화.', examples: ['A하이 보드 밸류', 'KQx 컨트롤'] },
    ATs: { action: 'R', reason: '수딧 A', detailedReason: '세미블러프 자원 풍부.', examples: ['턴 배럴 카드 많음'] },
    A9s: { action: 'R', reason: '마진 수딧 A', detailedReason: 'BTN 포지션으로 EV 확보.', examples: ['타이트 블라인드면 오픈 가치↑'] },
    A8s: { action: 'R', reason: '마진 수딧 A', detailedReason: 'BTN 포지션으로 EV 확보. 스틸 + 세미블러프.', examples: ['스틸 빈도↑'] },
    A7s: { action: 'R', reason: '수딧 A(하위)', detailedReason: '백도어/세미블러프 경로 多.', examples: ['턴에서 이퀴티 상승'] },
    A6s: { action: 'R', reason: '수딧 A(하위)', detailedReason: '백도어/세미블러프 경로 多. 포지션 우위.', examples: ['리버 블러프 카드 활용'] },
    A5s: { action: 'R', reason: '휠 + 넛 플러시', detailedReason: '포지션 우위로 적극 운영.', examples: ['런너런너 드로우 배럴'] },
    A4s: { action: 'R', reason: '휠 계열', detailedReason: '포지션 우위로 적극 운영. 휠/넛 플러시 잠재력.', examples: ['백도어 활용'] },
    A3s: { action: 'R', reason: '휠 계열(하위)', detailedReason: '포지션 우위로 적극 운영. 휠/넛 플러시 잠재력.', examples: ['블라인드 타이트시 오픈↑'] },
    A2s: { action: 'R', reason: '휠 계열(하위)', detailedReason: '포지션 우위로 적극 운영. 휠/넛 플러시 잠재력.', examples: ['스틸 목적'] },

    KQs: { action: 'R', reason: '수딧 브로드웨이', detailedReason: '강력 텍스처 커버리지.', examples: ['JTx/T9x 강공'] },
    KJs: { action: 'R', reason: '수딧 킹', detailedReason: '포지션으로 약키커 보정.', examples: ['Kxx 밸류'] },
    KTs: { action: 'R', reason: '수딧 킹(마진)', detailedReason: '도미네이션 리스크 있지만 포지션으로 보정.', examples: ['블라인드 성향에 맞춤'] },
    K9s: { action: 'R', reason: '수딧 킹(하위)', detailedReason: '스틸 + 세미블러프.', examples: ['히트 없으면 저렴히 포기'] },
    QJs: { action: 'R', reason: '수딧 퀸', detailedReason: '세미블러프 라인 다수.', examples: ['더블배럴 카드 풍부'] },
    QTs: { action: 'R', reason: '수딧 퀸(마진)', detailedReason: '포지션 보정.', examples: ['턴 압박'] },
    JTs: { action: 'R', reason: '수딧 커넥터', detailedReason: '가려진 밸류/블러프 라인.', examples: ['리버 블러프 카드 많음'] },
    T9s: { action: 'R', reason: '수딧 커넥터', detailedReason: '스틸 가치 + 플레이어빌리티.', examples: ['백도어 스트/플러시 활용'] },
    '98s': { action: 'R', reason: '수딧 커넥터', detailedReason: '포지션으로 컨트롤 용이.', examples: ['히트 없으면 C-bet 빈도↓'] },
    '87s': { action: 'R', reason: '수딧 커넥터(하위)', detailedReason: '포지션으로 컨트롤 용이. 스틸 가치 + 플레이어빌리티.', examples: ['라이트 스틸'] },
    '76s': { action: 'R', reason: '수딧 커넥터(하위)', detailedReason: '포지션으로 컨트롤 용이. 스틸 가치 + 플레이어빌리티.', examples: ['턴에서 압박'] },
    '65s': { action: 'R', reason: '수딧 커넥터(하위)', detailedReason: '포지션으로 컨트롤 용이. 스틸 가치 + 플레이어빌리티.', examples: ['리버 얇은 밸류는 자제'] },

    AKo: { action: 'R', reason: '강력 오프수트', detailedReason: '탑페어 가치 + 스틸.', examples: ['3-bet 콜/4-bet 믹스'] },
    AQo: { action: 'R', reason: '강력 오프수트', detailedReason: 'BTN 포지션으로 수익성↑.', examples: ['AQx 얇은 밸류'] },
    AJo: { action: 'R', reason: '오프수트 A', detailedReason: '후반 포지션 보정.', examples: ['라그 블라인드 상대로 컨트롤'] },
    ATo: { action: 'R', reason: '오프수트 A(마진)', detailedReason: '포지션으로 커버.', examples: ['3-bet 빈번시 폴드'] },
    KQo: { action: 'R', reason: '오프수트 브로드웨이', detailedReason: '브로드웨이 콤보 우수.', examples: ['KQx 밸류'] },
    KJo: { action: 'R', reason: '오프수트 킹', detailedReason: '포지션으로 보정.', examples: ['스틸 빈도↑'] },
    QJo: { action: 'R', reason: '오프수트 퀸', detailedReason: '포지션으로 보정. 스틸 + 세미블러프.', examples: ['히트 없으면 포기 빠르게'] },
    KTo: { action: 'M', reason: '경계선 오프수트', detailedReason: '상대/스택/이미지에 따라 혼합.', examples: ['타이트 블라인드 오픈', '공격적 3-bet 폴드'] },
    QTo: { action: 'M', reason: '경계선 오프수트', detailedReason: '혼합 사용.', examples: ['스틸 목적 소량'] },
    JTo: { action: 'M', reason: '경계선 오프수트', detailedReason: '혼합 사용.', examples: ['상대 폴드 성향 크면 오픈'] },
  },

  SB: {
    AA: { action: 'R', reason: '프리미엄', detailedReason: '포지션 최악이지만 블라인드 전용 스팟. 오픈/리스틸 EV 큼.', examples: ['작은 오픈으로 콜 유도', '3-bet/4-bet 라인'] },
    KK: { action: 'R', reason: '프리미엄', detailedReason: '포지션 최악이지만 블라인드 전용 스팟. 오픈/리스틸 EV 큼.', examples: ['A하이 보드 컨트롤'] },
    QQ: { action: 'R', reason: '프리미엄', detailedReason: '포지션 최악이지만 블라인드 전용 스팟. 오픈/리스틸 EV 큼.', examples: ['브릭 보드 강공'] },
    JJ: { action: 'R', reason: '강한 페어', detailedReason: 'OOP라 주도권 중요.', examples: ['C-bet 빈도↑'] },
    TT: { action: 'R', reason: '중상급 페어', detailedReason: 'OOP 리얼라이제이션 낮아 레이즈 선호.', examples: ['셋 미스 시 컨트롤'] },
    '99': { action: 'R', reason: '중페어', detailedReason: 'OOP 리얼라이제이션 낮아 레이즈 선호. 완전 OOP라 오픈/아이솔레이트로 EV 확보.', examples: ['블라인드 전용 스팟에서 강공'] },
    '88': { action: 'R', reason: '중페어', detailedReason: 'OOP 리얼라이제이션 낮아 레이즈 선호. 완전 OOP라 오픈/아이솔레이트로 EV 확보.', examples: ['리버 얇은 밸류 자제'] },
    '77': { action: 'R', reason: '중페어', detailedReason: 'OOP 리얼라이제이션 낮아 레이즈 선호. 완전 OOP라 오픈/아이솔레이트로 EV 확보.', examples: ['멀티웨이 최소화'] },
    '66': { action: 'R', reason: '로우 페어', detailedReason: '완전 OOP라 오픈/아이솔레이트로 EV 확보.', examples: ['셋 마이닝 + 컨트롤'] },
    '55': { action: 'R', reason: '로우 페어', detailedReason: '완전 OOP라 오픈/아이솔레이트로 EV 확보. 셋 마이닝 + 컨트롤.', examples: ['하이보드 체크/폴드'] },
    '44': { action: 'R', reason: '로우 페어', detailedReason: '완전 OOP라 오픈/아이솔레이트로 EV 확보. 셋 마이닝 + 컨트롤.', examples: ['딥스택에서 가치↑'] },
    '33': { action: 'R', reason: '로우 페어', detailedReason: '완전 OOP라 오픈/아이솔레이트로 EV 확보. 셋 마이닝 + 컨트롤.', examples: ['립-레 이즈보다 레이즈 선호'] },
    '22': { action: 'R', reason: '로우 페어', detailedReason: '완전 OOP라 오픈/아이솔레이트로 EV 확보. 셋 마이닝 + 컨트롤.', examples: ['상대 폴드 성향↑면 이득'] },

    AKs: { action: 'R', reason: '프리미엄 수딧', detailedReason: 'OOP라 콜보다 레이즈로 주도권.', examples: ['3-bet 강하게 대응'] },
    AQs: { action: 'R', reason: '강한 수딧', detailedReason: 'OOP라 콜보다 레이즈로 주도권. 탑페어/넛 드로우 라인.', examples: ['AQx 밸류'] },
    AJs: { action: 'R', reason: '수딧 A', detailedReason: 'OOP라 콜보다 레이즈로 주도권. 백도어/세미블러프 잠재력.', examples: ['백도어 배럴'] },
    ATs: { action: 'R', reason: '수딧 A', detailedReason: 'OOP라 콜보다 레이즈로 주도권. 백도어/세미블러프 잠재력.', examples: ['턴 압박'] },
    A9s: { action: 'R', reason: '마진 수딧 A', detailedReason: 'OOP 불리 보정 위해 레이즈 빈도↑.', examples: ['스틸/리스틸 목적'] },
    A8s: { action: 'R', reason: '마진 수딧 A', detailedReason: 'OOP 불리 보정 위해 레이즈 빈도↑. 스틸/리스틸 목적.', examples: ['상대 폴드 성향 크면 이득'] },
    A7s: { action: 'R', reason: '하위 수딧 A', detailedReason: 'OOP 불리 보정 위해 레이즈 빈도↑. 스틸/리스틸 목적.', examples: ['히트 없으면 컨트롤'] },
    A6s: { action: 'R', reason: '하위 수딧 A', detailedReason: 'OOP 불리 보정 위해 레이즈 빈도↑. 스틸/리스틸 목적.', examples: ['백도어 활용'] },
    A5s: { action: 'R', reason: '휠 + 넛 플러시', detailedReason: 'OOP 핸디캡을 적극성으로 상쇄.', examples: ['린프보다 레이즈'] },
    A4s: { action: 'R', reason: '휠 계열', detailedReason: 'OOP 핸디캡을 적극성으로 상쇄. 휠/넛 플러시 잠재력.', examples: ['리버 얇은 밸류 지양'] },
    A3s: { action: 'R', reason: '휠 계열(하위)', detailedReason: 'OOP 핸디캡을 적극성으로 상쇄. 휠/넛 플러시 잠재력.', examples: ['플랍 미스 시 빠른 포기'] },
    A2s: { action: 'R', reason: '휠 계열(하위)', detailedReason: 'OOP 핸디캡을 적극성으로 상쇄. 휠/넛 플러시 잠재력.', examples: ['상대 폴드 성향 읽기'] },

    KQs: { action: 'R', reason: '수딧 브로드웨이', detailedReason: 'OOP라 레이즈로 주도권.', examples: ['드로우 보드 강공'] },
    KJs: { action: 'R', reason: '수딧 킹', detailedReason: 'OOP라 레이즈로 주도권. 백도어/세미블러프 잠재력.', examples: ['턴 배럴'] },
    KTs: { action: 'R', reason: '수딧 킹(마진)', detailedReason: 'OOP라 레이즈로 주도권. 백도어/세미블러프 잠재력.', examples: ['히트 없으면 포기'] },
    QJs: { action: 'R', reason: '수딧 퀸', detailedReason: 'OOP라 레이즈로 주도권. 백도어/세미블러프 잠재력.', examples: ['세미블러프 자주'] },
    QTs: { action: 'R', reason: '수딧 퀸(마진)', detailedReason: 'OOP라 레이즈로 주도권. 백도어/세미블러프 잠재력.', examples: ['상대 콜빈도 낮을 때 압박'] },
    JTs: { action: 'R', reason: '수딧 커넥터', detailedReason: 'OOP라 레이즈로 주도권. 스틸 가치 + 플레이어빌리티.', examples: ['멀티웨이 최소화'] },
    T9s: { action: 'R', reason: '수딧 커넥터', detailedReason: 'OOP라 레이즈로 주도권. 스틸 가치 + 플레이어빌리티.', examples: ['보드 히트 없으면 컨트롤'] },
    '98s': { action: 'R', reason: '수딧 커넥터', detailedReason: 'OOP라 레이즈로 주도권. 스틸 가치 + 플레이어빌리티.', examples: ['스틸 빈도↑'] },
    '87s': { action: 'R', reason: '수딧 커넥터(하위)', detailedReason: 'OOP라 레이즈로 주도권. 스틸 가치 + 플레이어빌리티.', examples: ['딥스택에서만 확장'] },
    '76s': { action: 'R', reason: '수딧 커넥터(하위)', detailedReason: 'OOP라 레이즈로 주도권. 스틸 가치 + 플레이어빌리티.', examples: ['상대 성향 보고 결정'] },
    '65s': { action: 'R', reason: '수딧 커넥터(하위)', detailedReason: 'OOP라 레이즈로 주도권. 스틸 가치 + 플레이어빌리티.', examples: ['린프보다 레이즈 선호'] },

    AKo: { action: 'R', reason: '강력 오프수트', detailedReason: 'OOP라 주도권 필수.', examples: ['3-bet 빈도↑'] },
    AQo: { action: 'R', reason: '오프수트 A', detailedReason: 'OOP라 주도권 필수. 3-bet 빈도↑.', examples: ['AQx 밸류, K하이 컨트롤'] },
    AJo: { action: 'R', reason: '오프수트 A(마진)', detailedReason: 'OOP라 주도권 필수. 3-bet 빈도↑.', examples: ['어그로 테이블 빈도↓'] },
    ATo: { action: 'R', reason: '오프수트 A(하위)', detailedReason: 'OOP라 주도권 필수. 3-bet 빈도↑.', examples: ['히트 없으면 포기'] },
    KQo: { action: 'R', reason: '오프수트 브로드웨이', detailedReason: 'OOP라 주도권 필수. 3-bet 빈도↑.', examples: ['3-bet 큰 사이즈 폴드'] },
    KJo: { action: 'R', reason: '오프수트 킹', detailedReason: 'OOP라 주도권 필수. 3-bet 빈도↑.', examples: ['상대 폴드 성향↑면 이득'] },
    QJo: { action: 'R', reason: '오프수트 퀸', detailedReason: 'OOP라 주도권 필수. 3-bet 빈도↑.', examples: ['컨트롤 위주'] },
  },

  BB: {
    AA: { action: 'R', reason: '3-bet 밸류', detailedReason: '오픈에 대해 콜만 하기엔 손실. 3-bet으로 SPR 낮추고 밸류 극대화.', examples: ['작은 오픈엔 큰 3-bet', '멀티웨이 방지'] },
    KK: { action: 'R', reason: '3-bet 밸류', detailedReason: '오픈에 대해 콜만 하기엔 손실. 3-bet으로 SPR 낮추고 밸류 극대화.', examples: ['A보드 컨트롤', '4-bet 대응'] },
    QQ: { action: 'R', reason: '3-bet 빈도 높음', detailedReason: '콜은 멀티웨이 유도되어 EV 손실. 3-bet 주도권 선호.', examples: ['포지션 불리 보정'] },
    JJ: { action: 'R', reason: '3-bet 선호', detailedReason: '상대 오픈 레인지에 앞서는 구간 다수.', examples: ['딥스택 콜 혼합'] },

    TT: { action: 'C', reason: '콜 선호', detailedReason: '셋 마이닝 + 가격 방어. 큰 3-bet은 부담.', examples: ['작은 오픈엔 콜', '3-bet은 상황 제한'] },
    '99': { action: 'C', reason: '콜', detailedReason: '셋 마이닝 중심 운영.', examples: ['오버카드 많으면 체크/폴드'] },
    '88': { action: 'C', reason: '콜', detailedReason: '셋 마이닝 중심 운영. 오버카드 많으면 체크/폴드.', examples: ['턴에서 개선 없으면 포기'] },
    '77': { action: 'C', reason: '콜', detailedReason: '셋 마이닝 중심 운영. 오버카드 많으면 체크/폴드.', examples: ['딥스택일수록 콜 가치↑'] },
    '66': { action: 'C', reason: '콜', detailedReason: '셋 마이닝 중심 운영. 오버카드 많으면 체크/폴드.', examples: ['3-bet 거의 X'] },
    '55': { action: 'C', reason: '콜', detailedReason: '셋 마이닝 중심 운영. 오버카드 많으면 체크/폴드.', examples: ['리버 얇은 밸류 자제'] },

    AKs: { action: 'R', reason: '3-bet 밸류', detailedReason: '블로커 + 넛 잠재력. 콜보다 주도권 선호.', examples: ['후반 포지션 오픈엔 특히 강함'] },
    AQs: { action: 'C', reason: '콜 선호', detailedReason: '수딧 보정으로 콜 플레이 용이. 후반 오픈 상대로 3-bet 혼합.', examples: ['플랍 이퀴티로 압박'] },
    AJs: { action: 'C', reason: '콜', detailedReason: '역도미네이션/포지션 불리 감안.', examples: ['보드 히트 없으면 빠르게 포기'] },
    ATs: { action: 'C', reason: '콜', detailedReason: '역도미네이션/포지션 불리 감안. 백도어/세미블러프 잠재력.', examples: ['백도어 플랜'] },
    A9s: { action: 'C', reason: '콜', detailedReason: '역도미네이션/포지션 불리 감안. 백도어/세미블러프 잠재력.', examples: ['턴 배럴 제한'] },
    A8s: { action: 'C', reason: '콜', detailedReason: '역도미네이션/포지션 불리 감안. 백도어/세미블러프 잠재력.', examples: ['리버 블러프 카드 주의'] },
    A5s: { action: 'C', reason: '콜', detailedReason: '휠/플러시 세미블러프 잠재력.', examples: ['턴에 이퀴티 상승 기대'] },
    A4s: { action: 'C', reason: '콜', detailedReason: '휠/플러시 세미블러프 잠재력. 역도미네이션/포지션 불리 감안.', examples: ['상대 사이즈 크면 폴드'] },
    A3s: { action: 'C', reason: '콜', detailedReason: '휠/플러시 세미블러프 잠재력. 역도미네이션/포지션 불리 감안.', examples: ['히트 없으면 포기'] },
    A2s: { action: 'C', reason: '콜', detailedReason: '휠/플러시 세미블러프 잠재력. 역도미네이션/포지션 불리 감안.', examples: ['백도어 의존'] },

    KQs: { action: 'C', reason: '콜', detailedReason: '플레이어빌리티 양호.', examples: ['JTx 보드 공격 기회'] },
    KJs: { action: 'C', reason: '콜', detailedReason: '플레이어빌리티 양호. 멀티웨이에서도 OK.', examples: ['히트 없으면 포기'] },
    QJs: { action: 'C', reason: '콜', detailedReason: '플레이어빌리티 양호. 멀티웨이에서도 OK.', examples: ['세미블러프 기회'] },
    JTs: { action: 'C', reason: '콜', detailedReason: '플레이어빌리티 양호. 멀티웨이에서도 OK.', examples: ['백도어 활용'] },
    T9s: { action: 'C', reason: '콜', detailedReason: '플레이어빌리티 양호. 멀티웨이에서도 OK.', examples: ['턴 배럴 선택적'] },
    '98s': { action: 'C', reason: '콜', detailedReason: '플레이어빌리티 양호. 멀티웨이에서도 OK.', examples: ['멀티웨이에서도 OK'] },
    '87s': { action: 'C', reason: '콜', detailedReason: '플레이어빌리티 양호. 멀티웨이에서도 OK.', examples: ['리버 블러프 빈도 낮춤'] },

    AKo: { action: 'R', reason: '3-bet 밸류', detailedReason: '콜은 스퀴즈/멀티웨이 리스크. 3-bet으로 주도권.', examples: ['오픈 사이즈 크면 3-bet 사이즈↑'] },
    AQo: { action: 'C', reason: '콜/혼합', detailedReason: '오프수트 리얼라이제이션 낮음. 사이즈/상대 따라 혼합.', examples: ['후반 오픈엔 3-bet 일부'] },
    AJo: { action: 'C', reason: '콜', detailedReason: '오프수트 도미네이션 리스크. 콜이 무난.', examples: ['브로드웨이 보드 컨트롤'] },
    KQo: { action: 'C', reason: '콜', detailedReason: '오프수트 브로드웨이. 플랍 오버카드 다수 가능.', examples: ['히트 없으면 빠른 포기'] },
  },
};
